apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: board-prd
nameSuffix: -prd
resources:
- ../base

## 변경될 부분 지정
patches:
  - path: patch/namespace-patch.yaml
    target:
      kind: Namespace
  - path: patch/deployment-patch.yaml
    target:
      kind: Deployment
  - path: patch/route-patch.yaml
    target:
      kind: Route
  - path: patch/pipeline-patch.yaml
    target:
      kind: Pipeline