apiVersion: v1
items:
- apiVersion: argoproj.io/v1beta1
  kind: ArgoCD
  metadata:
    name: openshift-gitops
    namespace: openshift-gitops
  spec:
    applicationSet:
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      webhookServer:
        ingress:
          enabled: false
        route:
          enabled: false
    controller:
      processors: {}
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi
      sharding: {}
    grafana:
      enabled: false
      ingress:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      route:
        enabled: false
    ha:
      enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    initialSSHKnownHosts: {}
    monitoring:
      enabled: false
    notifications:
      enabled: false
    prometheus:
      enabled: false
      ingress:
        enabled: false
      route:
        enabled: false
    rbac:
      defaultPolicy: ""
      policy: |
        p, role:default, applications, get, */*, deny
        p, role:default, certificates, get, *, deny
        p, role:default, clusters, get, *, deny
        p, role:default, repositories, get, *, allow
        p, role:default, projects, get, *, deny
        p, role:default, accounts, get, *, deny
        p, role:default, gpgkeys, get, *, deny
        g, cluster-admin-group, role:admin
        g, system:cluster-admins, role:admin
        g, cluster-admins, role:admin
      scopes: '[groups]'
    redis:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    repo:
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
    resourceExclusions: |
      - apiGroups:
        - tekton.dev
        clusters:
        - '*'
        kinds:
        - TaskRun
        - PipelineRun
    server:
      autoscale:
        enabled: false
      grpc:
        ingress:
          enabled: false
      ingress:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 125m
          memory: 128Mi
      route:
        enabled: true
      service:
        type: ""
    sso:
      dex:
        groups:
        - default
        - cluster-admin-group
        openShiftOAuth: true
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
      provider: dex
    tls:
      ca: {}
  status:
    applicationController: Running
    applicationSetController: Running
    host: openshift-gitops-server-openshift-gitops.apps.poc.amc
    phase: Available
    redis: Running
    repo: Running
    server: Running
    sso: Running
kind: List
metadata:
  resourceVersion: ""
