apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: board-qa
nameSuffix: -qa
resources:
- ../base

## 변경될 부분 지정
patches:
  - path: patch/deployment-patch.yaml
    target:
      kind: Deployment
  - path: patch/route-patch.yaml
    target:
      kind: Route
  - path: patch/pipeline-patch.yaml
    target:
      kind: Pipeline
  - path: patch/secret-patch.yaml
    target:
      kind: Secret
      name: gitlab-secret
  - path: patch/serviceaccount-patch.yaml
    target:
      kind: ServiceAccount
      name: pipeline
#  - path: patch/namespace-patch.yaml
#    target:
#      kind: Namespace