kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: analyzer-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: thin-csi
  volumeMode: Filesystem
