kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonConfig
      name: config
      controller: true
      blockOwnerDeletion: true
secrets:
  - name: gitlab-secret