kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: job-buildconfig
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'image-registry.openshift-image-registry.svc:5000/job/job:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8'
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://gitlab.poc.amc:9443/root/san-poc.git'
    contextDir: job
  runPolicy: Serial
