apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/job-name: job
        job-name: job
      name: pi
    spec:
      containers:
      - command:
        - curl
        - http://job.apps.poc.amc/count
        image: perl
        imagePullPolicy: Always
        name: pi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
