apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aaaa
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/test-job/a:v1
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: san-poc/canary-image/a
    git:
      uri: https://gitlab.poc.amc:9443/root/san-poc.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: GIT_SSL_NO_VERIFY
        value: "true"
      from:
        kind: ImageStreamTag
        name: python:3.11-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
