apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: deploy-test
spec:
  clusterIP: 172.30.206.190
  clusterIPs:
  - 172.30.206.190
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: blue
  sessionAffinity: None
  type: ClusterIP
